spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:OnlineShop;IGNORECASE=TRUE
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode:
        always